name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build and push image
      - name: Build and push Vue Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vue-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vue-app:latest

      # 4. Deploy on server
      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_SERVER_IP}}
          username: ${{ secrets.DO_SERVER_USER}}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /root/inconel


            # deploy with latest images
            docker-compose -f inconel.yml up -d --pull always
