name: Deploy Static Site (with backup in /root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy files to /root/choir-website
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            mkdir -p /root/choir-website
          EOF

          scp -r . ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/root/choir-website/

      - name: Sync to /var/www/choir_website
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            sudo mkdir -p /var/www/choir_website
            sudo rm -rf /var/www/choir_website/*
            sudo cp -r /root/choir-website/* /var/www/choir_website/
            sudo chown -R www-data:www-data /var/www/choir_website
          EOF


      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} "systemctl restart nginx"
