name: Deploy Static Site (with backup in /root)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure backup folder exists on droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            mkdir -p /root/choir-website
          EOF

      - name: Sync project files to droplet (add/update/delete)
        run: |
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }}:/root/choir-website/

      - name: Deploy using harmony.yml with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_HOST }} << 'EOF'
            cd /root/choir-website
            docker-compose -f /root/harmony.yml down
            docker-compose -f /root/harmony.yml up -d --build
          EOF
